export const environment = {
  production: true,
  apiUrl: 'https://sisgesprovial.azurewebsites.net/api/',
  key:'AIzaSyCIDUBM6nFG-SXXeuRA3V9JAWv8ZUlKbcw3EWS',
  services:{
    user:"user.php",
    vendors:"vendors.php",
    conection:"conection.php",
    vendor:"vendor.php",
    'wenfare-fund':"wenfare-fund.php",
    charges:"charges.php",
    category:"category.php",
    cities:"cities.php",
    status:"status.php",
    countries:"countries.php",
    pension:"pension.php",
    roll:"roll.php",
    health:"health.php",
    "type-ids":"type-ids.php",
    "type-units":"type-units.php",
    states:"states.php",
    acquisition:"acquisition.php",
    acquisitions:"acquisitions.php",
    quotation:"quotation.php",
    quotations:"quotations.php",
    employees:"employees.php",
    projects:"projects.php",
    project:"project.php",
    clients:"clients.php",
    materials:"materials.php",
    users:"users.php"
  }
};
